/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practicas_basicas;

import java.awt.Color;

/**
 *
 * @author Hack
 */
public class Manejo_de_JMenuBar extends javax.swing.JFrame {

    /**
     * Creates new form Manejo_de_JMenuBar
     */
    public Manejo_de_JMenuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra_Menus = new javax.swing.JMenuBar();
        Menu_Archivo = new javax.swing.JMenu();
        Item_Abrir = new javax.swing.JMenuItem();
        Item_Guardar = new javax.swing.JMenuItem();
        Separador1 = new javax.swing.JPopupMenu.Separator();
        Menu_Salir = new javax.swing.JMenuItem();
        Menu_Edicion = new javax.swing.JMenu();
        Menu_Colores = new javax.swing.JMenu();
        Menu_ItemRojo = new javax.swing.JMenuItem();
        Menu_ItemVerde = new javax.swing.JMenuItem();
        Menu_ItemAzul = new javax.swing.JMenuItem();
        Menu_Insertar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu_Archivo.setText("Archivo");

        Item_Abrir.setText("Abrir");
        Item_Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_AbrirActionPerformed(evt);
            }
        });
        Menu_Archivo.add(Item_Abrir);

        Item_Guardar.setText("Guardar");
        Menu_Archivo.add(Item_Guardar);
        Menu_Archivo.add(Separador1);

        Menu_Salir.setText("Salir");
        Menu_Archivo.add(Menu_Salir);

        Barra_Menus.add(Menu_Archivo);

        Menu_Edicion.setText("Edición");

        Menu_Colores.setText("Colores");

        Menu_ItemRojo.setText("Rojo");
        Menu_ItemRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ItemRojoActionPerformed(evt);
            }
        });
        Menu_Colores.add(Menu_ItemRojo);

        Menu_ItemVerde.setText("Verde");
        Menu_ItemVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ItemVerdeActionPerformed(evt);
            }
        });
        Menu_Colores.add(Menu_ItemVerde);

        Menu_ItemAzul.setText("Azul");
        Menu_ItemAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ItemAzulActionPerformed(evt);
            }
        });
        Menu_Colores.add(Menu_ItemAzul);

        Menu_Edicion.add(Menu_Colores);

        Barra_Menus.add(Menu_Edicion);

        Menu_Insertar.setText("Insertar");
        Barra_Menus.add(Menu_Insertar);

        setJMenuBar(Barra_Menus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_AbrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Item_AbrirActionPerformed

    private void Menu_ItemRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ItemRojoActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.RED);
    }//GEN-LAST:event_Menu_ItemRojoActionPerformed

    private void Menu_ItemVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ItemVerdeActionPerformed
        // TODO add your handling code here:
         this.getContentPane().setBackground(Color.GREEN);
    }//GEN-LAST:event_Menu_ItemVerdeActionPerformed

    private void Menu_ItemAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ItemAzulActionPerformed
        // TODO add your handling code here:
         this.getContentPane().setBackground(Color.BLUE);
    }//GEN-LAST:event_Menu_ItemAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manejo_de_JMenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manejo_de_JMenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manejo_de_JMenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manejo_de_JMenuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manejo_de_JMenuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_Menus;
    private javax.swing.JMenuItem Item_Abrir;
    private javax.swing.JMenuItem Item_Guardar;
    private javax.swing.JMenu Menu_Archivo;
    private javax.swing.JMenu Menu_Colores;
    private javax.swing.JMenu Menu_Edicion;
    private javax.swing.JMenu Menu_Insertar;
    private javax.swing.JMenuItem Menu_ItemAzul;
    private javax.swing.JMenuItem Menu_ItemRojo;
    private javax.swing.JMenuItem Menu_ItemVerde;
    private javax.swing.JMenuItem Menu_Salir;
    private javax.swing.JPopupMenu.Separator Separador1;
    // End of variables declaration//GEN-END:variables
}
